const bundleMapping = {
  Button: 'button',
  Card: 'card',
  Checkbox: 'checkbox',
  Chips: 'chips',
  Dialog: 'dialog',
  Drawer: 'drawer',
  Elevation: 'elevation',
  Fab: 'fab',
  FormField: 'form-field',
  GridList: 'grid-list',
  Icon: 'icon-toggle',
  IconToggle: 'icon-toggle',
  ImageList: 'image-list',
  LayoutGrid: 'layout-grid',
  LinearProgress: 'linear-progress',
  LineRipple: 'line-ripple',
  List: 'list',
  Menu: 'menu',
  Tabs: 'tabs',
  Radio: 'radio',
  Select: 'select',
  Slider: 'slider',
  Snackbar: 'snackbar',
  Switch: 'switch',
  TextField: 'textfield',
  Toolbar: 'toolbar',
  TopAppBar: 'top-app-bar',
  Theme: 'theme',
  Typography: 'typography'
};

module.exports = bundleMapping;
